on:
  issues:
    types: [opened, reopened, closed, deleted]
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run github issue notion sync"
    steps:
      - uses: actions/checkout@v2
      - name: create env file
        run: |
          touch .env
          echo PERSONAL_ACCESS_KEY=${{ secrets.PERSONAL_ACCESS_KEY }} >> .env
          echo NOTION_KEY=${{ secrets.NOTION_KEY }} >> .env
          echo NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }} >> .env
          echo REPO_OWNER=${{ secrets.REPO_OWNER }} >> .env
          echo REPO_NAME=${{ secrets.REPO_NAME }} >> .env
      - name: docker compose up
        run: docker-compose --env-file .env up
